### ISSUE TITLE
csscomb object in Atom config.cson not working.

### ISSUE THREAD

**Issue by danielbayley** [bruce/atom-csscomb#10]
I can't for the life of me get atom-csscomb to work when using the config.cson.

It does work if I add `'csscomb': 'csscomb'` which obviously reads that default configuration, but any other attempt at putting actual properties in the config.cson always fails.

The console outputs `Found user CSScomb config: 
Array[1]` so it seems like it's reading it but nothing happens.

Do you by any chance have a working config.cson I can look at?

**Comment by nilshendriks** [comment]
+1 Maybe a how-to would be nice.
