### ISSUE TITLE
Throws an error on //comments in sass files

### ISSUE THREAD

**Issue by danielbayley** [bruce/atom-csscomb#14]
I tested the latest csscomb from the command line with the same sass file and it worked fine, so the problem must be with this Atom package.

Basically, it fails when parsing comments that use the `//` syntax.

Maybe updating the csscomb node_module to the latest version would fix it?

**Comment by stramel** [comment]
Please try the latest release to see if this is still an issue. Thanks!

**Comment by danielbayley** [comment]
I don't actually use this package any more (switched to `atom-css-comb`). But just did a quick test and it seems to work ok. It may have been caused by having to put all that configuration into a resultantly bloated `config.cson`. Definitely not ideal. See #15/#8.

**Comment by stramel** [comment]
@danielbayley Thanks, I am hoping I can hop onto some of these issues and make the plugin work well again.
