### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by darcher-** [bruce/atom-csscomb#23]
In keymaps\csscomb.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by Arelav** [comment]
Same issue "Use the atom-workspace tag instead of the workspace class."

**Comment by stramel** [comment]
Addressed by PR #18 & #21. Should be in favor of PR #18.

**Comment by stramel** [comment]
This was merged into develop and release will hopefully be cut soon. Thank you for your patience.
