### ISSUE TITLE
How to add line break for option in config.cson file ?

### ISSUE THREAD

**Issue by ethyde** [bruce/atom-csscomb#36]
hi,

I try to add line break for some csscomb option, like "space-after-opening-brace" or "space-after-selector-delimiter" but "\n" has no effect in setting ( \n become "\n" in config file).

If i edit config.cson file and add "\n", it's work ! Until a need to add/remove or config any atom package.

Atom 1.0.19
Win 8.1

**Comment by stramel** [comment]
Hmm... strange, `"space-after-opening-brace": "\n",` should work. It will need looking into.

**Comment by ethyde** [comment]
Yes, it work, until next read/save of config.cson file.

Exemple : 
- "space-after-opening-brace": "\n",
- save file
- open any other package's config panel (Settings > Packages > any_package)
- and if i re-open my config.cson file : 
  ![atomscreen](https://cloud.githubusercontent.com/assets/409987/10249373/3f395706-6925-11e5-9c20-e54b34584be9.jpg)

**Comment by ethyde** [comment]
It's like there are a sort of "Format on save" for core system's files.

Because : 
"quotes": "single"
become : 
![atomscreen2](https://cloud.githubusercontent.com/assets/409987/10250976/32c28322-692e-11e5-91da-5db607bafc7c.jpg)

**Comment by programbo** [comment]
Well, I am glad it's not just me having this issue. Hope it can get fixed because the problem just got worse. This morning the number of spaces that replace the `\n` grows every second, and it's tricky to stop because the constantly updating CSON file makes it impossible to select text.

**Comment by rosszurowski** [comment]
I've also been running into this issue. After some searching around, it looks like this problem lies within the official [atom/settings-view](https://github.com/atom/settings-view) package, and is being tracked by atom/settings-view#560

**Comment by zeraphie** [comment]
This is quite infuriating I must say, it's my only qualm with this plugin, otherwise it's pretty much perfect for what I want. Perhaps a good way to get around it is to be able to specify the filepath for the global version of the csscomb until the bug is fixed?

**Comment by smulder** [comment]
2 years later and still an issue

**Comment by bruce** [comment]
@smulder This package is no longer maintained; I no longer use Atom. If someone wants to take it over, fork it (or even submit a PR), I'm happy to entertain their assistance.
